### ISSUE TITLE
icp 测试 需求

### ISSUE THREAD

**Issue by akakenle** [akakenle/icp-auth#2]
用于icp 认证测试

**Comment by akakenle** [comment]
@maohuaming 申请开发 size：3 Deadline: 2018-06-07

**Comment by maohuaming** [comment]
@akakenle 你这一操作有一个违规的地方，就是ICP标签应该由committer/mentor来操作。

**Comment by akakenle** [comment]
嗯，好的 @maohuaming

**Comment by maohuaming** [comment]
@akakenle 另外再提示一下，申请开发格式如下:
申请开发 deadline:yyyy-mm-dd size:xx @[committer]
这个格式流程图中可能没有更新，这个就不算违规了。

**Comment by akakenle** [comment]
嗯，我看流程图上是我那样格式的

**Comment by maohuaming** [comment]
@akakenle 记违规一次。请删除ICP标签。
